function createaxes(parent1, x1, y1)
%CREATEAXES(PARENT1,X1,Y1)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  Y1:  matrix of y data
 
%  Auto-generated by MATLAB on 28-Dec-2009 11:39:41
 
%% Create axes
axes1 = axes('Parent',parent1);
xlabel(axes1,'t (year)');
ylabel(axes1,'Normalized system failure probability');
grid(axes1,'on');
hold(axes1,'all');
 
%% Create multiple lines using matrix input to plot
plot1 = plot(x1,y1);
set(plot1(1),...
  'Color',[0 0 1],...
  'LineWidth',3);
set(plot1(2),...
  'Color',[0 0 1],...
  'LineStyle','-.',...
  'LineWidth',3);
 
saveas(gcf,'NormalizedSystemFailure.png')

